name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Gem / Release
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Credentials
      uses: fac/ruby-gem-setup-credentials-action@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Gem
      run: bundle exec rake build
    - name: Release Gem
      uses: fac/ruby-gem-push-action@v2
