name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Gem / Release
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build Gem
      run: |
        bundle install --jobs 4 --retry 3
        bundle exec rake build
    - name: Setup Credentials
      uses: fac/ruby-gem-setup-credentials-action@v2
      with:
        user: ""
        key: rubygems
        token: ${{secrets.RUBY_GEMS_API_KEY}}
    - name: Release Gem
      uses: fac/ruby-gem-push-action@v2
      with:
        key: rubygems
